// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCV_NLkzKpNcbcdu9XBYmJPqh6us60iTR8',
    appId: '1:821935943474:web:600e58c96bc431fecaf12b',
    messagingSenderId: '821935943474',
    projectId: 'campfire-88593',
    authDomain: 'campfire-88593.firebaseapp.com',
    storageBucket: 'campfire-88593.appspot.com',
    measurementId: 'G-Y54LRYBBY2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDAvGC9fz_J-8OREWAI8Irek7mUbSgEBU',
    appId: '1:821935943474:android:5865f981210bf4adcaf12b',
    messagingSenderId: '821935943474',
    projectId: 'campfire-88593',
    storageBucket: 'campfire-88593.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8pvgBcUNrzOb-IbGOhJrUFDyhJIIpvFw',
    appId: '1:821935943474:ios:1d4691b00eb86f9bcaf12b',
    messagingSenderId: '821935943474',
    projectId: 'campfire-88593',
    storageBucket: 'campfire-88593.appspot.com',
    iosBundleId: 'com.example.campfire',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8pvgBcUNrzOb-IbGOhJrUFDyhJIIpvFw',
    appId: '1:821935943474:ios:1d4691b00eb86f9bcaf12b',
    messagingSenderId: '821935943474',
    projectId: 'campfire-88593',
    storageBucket: 'campfire-88593.appspot.com',
    iosBundleId: 'com.example.campfire',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCV_NLkzKpNcbcdu9XBYmJPqh6us60iTR8',
    appId: '1:821935943474:web:1df3dd6f7f9068aecaf12b',
    messagingSenderId: '821935943474',
    projectId: 'campfire-88593',
    authDomain: 'campfire-88593.firebaseapp.com',
    storageBucket: 'campfire-88593.appspot.com',
    measurementId: 'G-EBCRSYHHKT',
  );
}
